 version: "3.7"

services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 
    restart: always
    ports:
      - "3306:3306"
    java:
      image: openjdk:12
      container_name: java
      depends_on: 
        - database
      volumes: ./home/deliverit/fourbanco:/usr/src/app
      working_dir: /usr/src/app
      command: bash -c "java -jar maven-wrapper.jar"
